name: 'Sync'

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      applications:
          description: 'url'
          required: false
          default: ''
          type: string

jobs:
  build:
    name: 'Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        if : ${{ github.event.inputs.applications }} != ''
        with:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
          url: ${{ github.event.inputs.applications }}
      
      - name: Async Github Branch To Gitee
      - uses: shanghaobo/github-branch-gitee@master
        with:
            github_repo: chenxudong2020/sync_gitee
            github_branch: main
            gitee_repo: opopop880/github_sync
            gitee_branch: master
            username: ${{ secrets.GITEE_USERNAME }}
            password: ${{ secrets.GITEE_PASSWORD }}    
