name: 'Sync'

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      applications:
          description: 'url'
          required: false
          default: ''
          type: string

jobs:
  build:
    name: 'Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Get app list
        id: apps_list
        run: |
            url="${{ github.event.inputs.applications }}"
            echo "url=$url" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        if: env.url != ''
        with:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
          url: ${{ github.event.inputs.applications }}
      - name: Sync to Gitee
        uses: chenxudong2020/sync-gitee-action@v1
        with:
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
          repository: opopop880/sync_gitee
