name: 'Sync'

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      applications:
          description: 'url'
          required: false
          default: ''
          type: string
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  sync:
    name: 'Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - id : downloadAndUpload
      - if : "${{ github.event.inputs.applications }}" != ""
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.inputs.applications }}