name: 'Sync'

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      applications:
          description: 'url'
          required: false
          default: ''
          type: string

jobs:
  build:
    name: 'Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: downloadAndUpload
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        id : downloadAndUpload
        if : ${{ github.event.inputs.applications }} != ''
        with:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
          url: ${{ github.event.inputs.applications }}
